import { ClipPoint, CustomComponent, ProfileElement, CanvasSettings } from '../types/profile';
import { GaiaComponentKind, createGaiaPanelElement, xForColumn } from './gaiaSpec';

export const CLIP_PRESETS: Record<string, { label: string; vertices: ClipPoint[] }> = {
  hexagon: {
    label: 'Hexagon',
    vertices: [
      { x: 25, y: 0 },
      { x: 75, y: 0 },
      { x: 100, y: 50 },
      { x: 75, y: 100 },
      { x: 25, y: 100 },
      { x: 0, y: 50 },
    ],
  },
  star: {
    label: '5-Point Star',
    vertices: [
      { x: 50, y: 0 },
      { x: 61, y: 35 },
      { x: 98, y: 35 },
      { x: 68, y: 57 },
      { x: 79, y: 91 },
      { x: 50, y: 70 },
      { x: 21, y: 91 },
      { x: 32, y: 57 },
      { x: 2, y: 35 },
      { x: 39, y: 35 },
    ],
  },
  beveled: {
    label: 'Cyber Beveled',
    vertices: [
      { x: 0, y: 15 },
      { x: 15, y: 0 },
      { x: 100, y: 0 },
      { x: 100, y: 85 },
      { x: 85, y: 100 },
      { x: 0, y: 100 },
    ],
  },
  rhombus: {
    label: 'Diamond Rhombus',
    vertices: [
      { x: 50, y: 0 },
      { x: 100, y: 50 },
      { x: 50, y: 100 },
      { x: 0, y: 50 },
    ],
  },
  badge: {
    label: 'Slanted Ribbon',
    vertices: [
      { x: 0, y: 0 },
      { x: 88, y: 0 },
      { x: 100, y: 50 },
      { x: 88, y: 100 },
      { x: 0, y: 100 },
      { x: 12, y: 50 },
    ],
  },
  octagon: {
    label: 'Octagon',
    vertices: [
      { x: 30, y: 0 },
      { x: 70, y: 0 },
      { x: 100, y: 30 },
      { x: 100, y: 70 },
      { x: 70, y: 100 },
      { x: 30, y: 100 },
      { x: 0, y: 70 },
      { x: 0, y: 30 },
    ],
  },
  chevron: {
    label: 'Chevron Arrow',
    vertices: [
      { x: 100, y: 0 },
      { x: 75, y: 50 },
      { x: 100, y: 100 },
      { x: 25, y: 100 },
      { x: 0, y: 50 },
      { x: 25, y: 0 },
    ],
  },
  crest: {
    label: 'Shield Crest',
    vertices: [
      { x: 0, y: 0 },
      { x: 100, y: 0 },
      { x: 100, y: 65 },
      { x: 50, y: 100 },
      { x: 0, y: 65 },
    ],
  },
};

export const MASK_PRESETS = [
  {
    id: 'fade-bottom',
    label: 'Fade to Bottom',
    type: 'linear-gradient',
    angle: 180,
    feather: 35,
    preview: 'linear-gradient(180deg, #6366f1 50%, transparent 100%)',
  },
  {
    id: 'radial-spotlight',
    label: 'Radial Spotlight',
    type: 'radial-gradient',
    angle: 0,
    feather: 40,
    preview: 'radial-gradient(circle, #6366f1 30%, transparent 85%)',
  },
  {
    id: 'vignette',
    label: 'Feather Vignette',
    type: 'preset',
    angle: 0,
    feather: 50,
    preview: 'radial-gradient(ellipse, #6366f1 20%, transparent 90%)',
  },
  {
    id: 'fade-horizontal',
    label: 'Horizontal Fade',
    type: 'linear-gradient',
    angle: 90,
    feather: 25,
    preview: 'linear-gradient(90deg, transparent 0%, #6366f1 25%, #6366f1 75%, transparent 100%)',
  },
  {
    id: 'diamond',
    label: 'Diamond Glow',
    type: 'preset',
    angle: 0,
    feather: 30,
    preview: 'radial-gradient(circle closest-side, #6366f1 30%, transparent 100%)',
  },
];

export const ANIMATION_PRESETS = [
  { id: 'float', label: 'Floating Hover', description: 'Gentle up and down levitation', icon: '🪶' },
  { id: 'neonPulse', label: 'Neon Glow Pulse', description: 'Intense pulsing glow effect', icon: '✨' },
  { id: 'glitchShake', label: 'Cyber Glitch', description: 'Jittery cybernetic displacement', icon: '⚡' },
  { id: 'shimmerSweep', label: 'Shimmer Sweep', description: 'Light passing across element', icon: '🌟' },
  { id: 'rotate3d', label: '3D Orbit Spin', description: 'Continuous Y-axis 3D rotation', icon: '🔄' },
  { id: 'heartbeat', label: 'Heartbeat Throb', description: 'Double pulse scale animation', icon: '💓' },
  { id: 'bounce', label: 'Playful Bounce', description: 'Springy vertical bounce', icon: '🏀' },
  { id: 'marquee', label: 'Retro Marquee', description: 'Infinite horizontal ticker scroll', icon: '📜' },
  { id: 'rainbowBorder', label: 'Chroma Hue Cycle', description: 'Cycling hue spectrum glow', icon: '🌈' },
  { id: 'fadeIn', label: 'Fade In Entrance', description: 'Smooth vertical reveal', icon: '👁️' },
  { id: 'cyberBlink', label: 'Terminal Blink', description: 'Authentic retro cursor blink', icon: '📟' },
  { id: 'morphBlob', label: 'Blob Morph', description: 'Organic blob cycling through corner radii', icon: '🫧' },
  { id: 'morphLiquid', label: 'Liquid Wobble', description: 'Soft pulsing blob with drifting radius', icon: '💧' },
  { id: 'morphCorners', label: 'Corner Shift', description: 'Square to capsule corner transformation', icon: '🔲' },
  { id: 'morphJelly', label: 'Jelly Squash', description: 'Squash-and-stretch elasticity', icon: '🍮' },
  { id: 'tilt3d', label: '3D Tilt Sway', description: 'Panel sways on the Y and X axes', icon: '🎴' },
  { id: 'flip3d', label: '3D Flip Card', description: 'Full Y-axis card flip with perspective', icon: '🃏' },
  { id: 'swing3d', label: 'Hanging Swing', description: 'Top-hinged 3D pendulum swing', icon: '🕰️' },
  { id: 'depthPop', label: 'Depth Pop', description: 'Pulses toward the viewer on the Z axis', icon: '🔭' },
];

export const DEFAULT_CUSTOM_COMPONENTS: CustomComponent[] = [
  {
    id: 'comp_cyber_avatar',
    title: 'Cyberpunk Hex Avatar',
    description: 'Masked hexagon avatar with cyan neon glow and floating levitation.',
    category: 'Avatars & Badges',
    previewColor: '#06b6d4',
    createdAt: Date.now() - 50000,
    elements: [
      {
        id: 'el_cyber_avatar',
        name: 'Hexagon Avatar',
        type: 'image',
        content: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
        colorMarker: '#1',
        useAttributeSelector: true,
        x: 40,
        y: 40,
        width: 140,
        height: 140,
        zIndex: 5,
        rotate: 0,
        opacity: 100,
        locked: false,
        hidden: false,
        color: '#06b6d4',
        backgroundColor: 'rgba(6, 182, 212, 0.1)',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fontFamily: 'inherit',
        borderWidth: 2,
        borderColor: '#06b6d4',
        borderStyle: 'solid',
        borderRadius: 0,
        boxShadow: '0 0 25px rgba(6, 182, 212, 0.5)',
        padding: 0,
        overflow: 'hidden',
        mask: {
          enabled: false,
          type: 'radial-gradient',
          preset: 'radial-spotlight',
          angle: 0,
          stops: [],
          feather: 30,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: true,
          type: 'polygon',
          preset: 'hexagon',
          vertices: CLIP_PRESETS.hexagon.vertices,
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: true,
          preset: 'neonPulse',
          duration: 2.2,
          delay: 0,
          timing: 'ease-in-out',
          iteration: 'infinite',
          direction: 'alternate',
          trigger: 'always',
        },
      },
    ],
  },
  {
    id: 'comp_glowing_quote',
    title: 'Holographic Quote Box',
    description: 'Slanted cyber quote container with violet accent and soft backdrop glow.',
    category: 'Cards & Quotes',
    previewColor: '#8b5cf6',
    createdAt: Date.now() - 40000,
    elements: [
      {
        id: 'el_glowing_quote',
        name: 'Holo Quote',
        type: 'quote',
        content: '"The code you write today shapes the neural reality of tomorrow."',
        colorMarker: '#2',
        useAttributeSelector: true,
        x: 210,
        y: 45,
        width: 440,
        height: 120,
        zIndex: 4,
        rotate: 0,
        opacity: 95,
        locked: false,
        hidden: false,
        color: '#e2e8f0',
        backgroundColor: 'rgba(23, 22, 45, 0.85)',
        fontSize: 16,
        fontWeight: 'normal',
        fontStyle: 'italic',
        textDecoration: 'none',
        textAlign: 'left',
        fontFamily: 'Georgia, serif',
        borderWidth: 1,
        borderColor: '#a855f7',
        borderStyle: 'solid',
        borderRadius: 8,
        boxShadow: '0 8px 32px rgba(168, 85, 247, 0.25)',
        backdropFilter: 'blur(12px)',
        padding: 18,
        overflow: 'hidden',
        mask: {
          enabled: true,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 15,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: true,
          type: 'polygon',
          preset: 'beveled',
          vertices: CLIP_PRESETS.beveled.vertices,
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: true,
          preset: 'float',
          duration: 4,
          delay: 0.5,
          timing: 'ease-in-out',
          iteration: 'infinite',
          direction: 'alternate',
          trigger: 'always',
        },
      },
    ],
  },
  {
    id: 'comp_terminal_card',
    title: 'Cyberpunk Code Console',
    description: 'Interactive monospace terminal box with green neon scanline styling.',
    category: 'Media & Embeds',
    previewColor: '#10b981',
    createdAt: Date.now() - 30000,
    elements: [
      {
        id: 'el_terminal_code',
        name: 'Terminal Status',
        type: 'code',
        content: `// [SYSTEM STATUS: ONLINE]\nconst netrunner = {\n  alias: 'ZeroCool',\n  faction: 'CyberVoid',\n  clearance: 'OMEGA',\n  ping: '12ms'\n};`,
        colorMarker: '#3',
        useAttributeSelector: true,
        x: 40,
        y: 200,
        width: 320,
        height: 145,
        zIndex: 3,
        rotate: 0,
        opacity: 100,
        locked: false,
        hidden: false,
        color: '#34d399',
        backgroundColor: 'rgba(6, 15, 25, 0.92)',
        fontSize: 13,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'left',
        fontFamily: "'Courier New', Courier, monospace",
        borderWidth: 1,
        borderColor: '#10b981',
        borderStyle: 'dashed',
        borderRadius: 6,
        boxShadow: '0 0 18px rgba(16, 185, 129, 0.25)',
        padding: 14,
        overflow: 'auto',
        mask: {
          enabled: false,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 0,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: false,
          type: 'polygon',
          preset: 'hexagon',
          vertices: [],
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: false,
          preset: 'fadeIn',
          duration: 1,
          delay: 0,
          timing: 'ease',
          iteration: '1',
          direction: 'normal',
          trigger: 'always',
        },
      },
    ],
  },
  {
    id: 'comp_synth_video',
    title: 'Synthwave Video Frame',
    description: 'Styled YouTube embed player with slanted clip and neon border.',
    category: 'Media & Embeds',
    previewColor: '#ec4899',
    createdAt: Date.now() - 20000,
    elements: [
      {
        id: 'el_synth_video',
        name: 'Featured Media',
        type: 'video',
        content: '5qap5aO4i9A', // Lofi synthwave sample
        colorMarker: '#4',
        useAttributeSelector: true,
        x: 380,
        y: 190,
        width: 270,
        height: 155,
        zIndex: 3,
        rotate: 0,
        opacity: 100,
        locked: false,
        hidden: false,
        color: '#ffffff',
        backgroundColor: '#0a0b12',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fontFamily: 'inherit',
        borderWidth: 2,
        borderColor: '#f43f5e',
        borderStyle: 'solid',
        borderRadius: 8,
        boxShadow: '0 0 24px rgba(244, 63, 94, 0.35)',
        padding: 0,
        overflow: 'hidden',
        mask: {
          enabled: false,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 0,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: false,
          type: 'polygon',
          preset: 'hexagon',
          vertices: [],
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: false,
          preset: 'float',
          duration: 3,
          delay: 0,
          timing: 'ease-in-out',
          iteration: 'infinite',
          direction: 'alternate',
          trigger: 'always',
        },
      },
    ],
  },
  {
    id: 'comp_badge_link',
    title: 'Neon Ribbon Link Button',
    description: 'Slanted interactive link button with hover pulse animation.',
    category: 'Accents & Borders',
    previewColor: '#f59e0b',
    createdAt: Date.now() - 10000,
    elements: [
      {
        id: 'el_badge_link',
        name: 'Profile Link Badge',
        type: 'link',
        content: '⚡ ACCESS MATRIX REPOSITORY',
        linkUrl: 'https://github.com',
        colorMarker: '#5',
        useAttributeSelector: true,
        x: 180,
        y: 375,
        width: 320,
        height: 48,
        zIndex: 5,
        rotate: 0,
        opacity: 100,
        locked: false,
        hidden: false,
        color: '#fbbf24',
        backgroundColor: 'rgba(245, 158, 11, 0.15)',
        fontSize: 14,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fontFamily: 'inherit',
        borderWidth: 2,
        borderColor: '#f59e0b',
        borderStyle: 'solid',
        borderRadius: 4,
        boxShadow: '0 0 15px rgba(245, 158, 11, 0.3)',
        padding: 12,
        overflow: 'hidden',
        mask: {
          enabled: false,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 0,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: true,
          type: 'polygon',
          preset: 'badge',
          vertices: CLIP_PRESETS.badge.vertices,
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: true,
          preset: 'glitchShake',
          duration: 0.4,
          delay: 0,
          timing: 'ease-in-out',
          iteration: 'infinite',
          direction: 'normal',
          trigger: 'hover',
        },
      },
    ],
  },
];

const GAIA_STARTER_SETTINGS: CanvasSettings = {
  width: 1380,
  height: 900,
  backgroundColor: '#0b1020',
  backgroundImage:
    'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1600&auto=format&fit=crop&q=70',
  backgroundRepeat: 'repeat',
  backgroundSize: 'cover',
  backgroundPosition: 'center top',
  gridSnap: true,
  gridSize: 10,
  showGrid: false,
  profileTitle: 'Gaia V2 Native Profile',
  forumTheme: 'dark-cyber',
};

/**
 * Starter profile built entirely from Gaia-supported components so the
 * generated CSS targets real V2 panel classes and ids from the first click.
 */
function buildGaiaStarterElements(): ProfileElement[] {
  const layout: Array<[GaiaComponentKind, 1 | 2 | 3]> = [
    ['details', 1],
    ['contact', 1],
    ['equipment', 1],
    ['about', 2],
    ['comments', 2],
    ['journal', 2],
    ['wishlist', 3],
    ['friends', 3],
    ['badges', 3],
  ];
  const cursor = new Map<number, number>();
  return layout.map(([kind, column], index) => {
    const element = createGaiaPanelElement(kind, column, index, GAIA_STARTER_SETTINGS);
    const row = cursor.get(column) || 0;
    cursor.set(column, row + 1);
    return {
      ...element,
      x: xForColumn(GAIA_STARTER_SETTINGS, column, element.width),
      y: 40 + row * 24,
      zIndex: index + 1,
      hidden: false,
    };
  });
}

export const STARTER_PROFILES: Record<
  string,
  { name: string; description: string; settings: CanvasSettings; elements: ProfileElement[] }
> = {
  gaiaV2: {
    name: 'Gaia V2 Native',
    description:
      'Built from Gaia-supported components only — Details, Contact, Comments, Friends, Badges and more, laid out in #columns.',
    settings: GAIA_STARTER_SETTINGS,
    elements: buildGaiaStarterElements(),
  },
  cyberpunk: {
    name: 'Cyberpunk Netrunner 2099',
    description: 'High-tech dark profile with neon cyan/magenta styling and polygon clipping.',
    settings: {
      width: 720,
      height: 600,
      backgroundColor: '#090b14',
      backgroundImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=70',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      gridSnap: true,
      gridSize: 10,
      showGrid: false,
      profileTitle: 'Netrunner Cyber Profile',
      forumTheme: 'dark-cyber',
    },
    elements: [
      // Avatar Hexagon
      {
        id: 'el_1',
        name: 'Cyber Avatar',
        type: 'image',
        content: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
        colorMarker: '#1',
        useAttributeSelector: true,
        x: 40,
        y: 40,
        width: 140,
        height: 140,
        zIndex: 10,
        rotate: 0,
        opacity: 100,
        locked: false,
        hidden: false,
        color: '#06b6d4',
        backgroundColor: '#06b6d4',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fontFamily: 'inherit',
        borderWidth: 2,
        borderColor: '#06b6d4',
        borderStyle: 'solid',
        borderRadius: 0,
        boxShadow: '0 0 30px rgba(6, 182, 212, 0.6)',
        padding: 0,
        overflow: 'hidden',
        mask: {
          enabled: false,
          type: 'radial-gradient',
          preset: 'radial-spotlight',
          angle: 0,
          stops: [],
          feather: 30,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: true,
          type: 'polygon',
          preset: 'hexagon',
          vertices: CLIP_PRESETS.hexagon.vertices,
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: true,
          preset: 'neonPulse',
          duration: 2.5,
          delay: 0,
          timing: 'ease-in-out',
          iteration: 'infinite',
          direction: 'alternate',
          trigger: 'always',
        },
      },
      // Title Header
      {
        id: 'el_2',
        name: 'Profile Title',
        type: 'text',
        content: 'CYBER//RUNNER // NULL_PTR',
        colorMarker: '#2',
        useAttributeSelector: true,
        x: 210,
        y: 40,
        width: 440,
        height: 48,
        zIndex: 5,
        rotate: 0,
        opacity: 100,
        locked: false,
        hidden: false,
        color: '#38bdf8',
        backgroundColor: 'rgba(15, 23, 42, 0.75)',
        fontSize: 22,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'left',
        fontFamily: "'Courier New', Courier, monospace",
        borderWidth: 1,
        borderColor: '#38bdf8',
        borderStyle: 'solid',
        borderRadius: 4,
        boxShadow: '0 0 15px rgba(56, 189, 248, 0.3)',
        backdropFilter: 'blur(8px)',
        padding: 10,
        overflow: 'hidden',
        mask: {
          enabled: false,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 0,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: true,
          type: 'polygon',
          preset: 'beveled',
          vertices: CLIP_PRESETS.beveled.vertices,
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: true,
          preset: 'shimmerSweep',
          duration: 3,
          delay: 0,
          timing: 'linear',
          iteration: 'infinite',
          direction: 'normal',
          trigger: 'always',
        },
      },
      // Quote Block
      {
        id: 'el_3',
        name: 'Status Quote',
        type: 'quote',
        content: '"High bandwidth, low latency, zero remorse in the neon digital sprawl."',
        colorMarker: '#3',
        useAttributeSelector: true,
        x: 210,
        y: 100,
        width: 440,
        height: 70,
        zIndex: 5,
        rotate: 0,
        opacity: 95,
        locked: false,
        hidden: false,
        color: '#e2e8f0',
        backgroundColor: 'rgba(20, 15, 38, 0.85)',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'italic',
        textDecoration: 'none',
        textAlign: 'left',
        fontFamily: 'Georgia, serif',
        borderWidth: 1,
        borderColor: '#a855f7',
        borderStyle: 'solid',
        borderRadius: 4,
        boxShadow: '0 4px 20px rgba(168, 85, 247, 0.25)',
        padding: 12,
        overflow: 'hidden',
        mask: {
          enabled: true,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 20,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: false,
          type: 'polygon',
          preset: 'hexagon',
          vertices: [],
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: true,
          preset: 'float',
          duration: 3.5,
          delay: 0.2,
          timing: 'ease-in-out',
          iteration: 'infinite',
          direction: 'alternate',
          trigger: 'always',
        },
      },
      // Code Block
      {
        id: 'el_4',
        name: 'System Code Terminal',
        type: 'code',
        content: `// [SYSTEM LOG: NODE #702]\nconnect('wss://matrix.net/feed');\nSTATUS: ENCRYPTED // LEVEL 5`,
        colorMarker: '#4',
        useAttributeSelector: true,
        x: 40,
        y: 205,
        width: 290,
        height: 165,
        zIndex: 4,
        rotate: 0,
        opacity: 95,
        locked: false,
        hidden: false,
        color: '#10b981',
        backgroundColor: 'rgba(5, 10, 20, 0.9)',
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'left',
        fontFamily: "'Courier New', Courier, monospace",
        borderWidth: 1,
        borderColor: '#059669',
        borderStyle: 'solid',
        borderRadius: 6,
        boxShadow: '0 0 20px rgba(16, 185, 129, 0.2)',
        padding: 12,
        overflow: 'auto',
        mask: {
          enabled: false,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 0,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: false,
          type: 'polygon',
          preset: 'hexagon',
          vertices: [],
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: false,
          preset: 'fadeIn',
          duration: 1,
          delay: 0,
          timing: 'ease',
          iteration: '1',
          direction: 'normal',
          trigger: 'always',
        },
      },
      // Video Frame
      {
        id: 'el_5',
        name: 'Lo-Fi Stream Video',
        type: 'video',
        content: '5qap5aO4i9A',
        colorMarker: '#5',
        useAttributeSelector: true,
        x: 350,
        y: 205,
        width: 330,
        height: 165,
        zIndex: 4,
        rotate: 0,
        opacity: 100,
        locked: false,
        hidden: false,
        color: '#ffffff',
        backgroundColor: '#000000',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fontFamily: 'inherit',
        borderWidth: 2,
        borderColor: '#ec4899',
        borderStyle: 'solid',
        borderRadius: 8,
        boxShadow: '0 0 20px rgba(236, 72, 153, 0.3)',
        padding: 0,
        overflow: 'hidden',
        mask: {
          enabled: false,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 0,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: false,
          type: 'polygon',
          preset: 'hexagon',
          vertices: [],
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: false,
          preset: 'float',
          duration: 3,
          delay: 0,
          timing: 'ease-in-out',
          iteration: 'infinite',
          direction: 'alternate',
          trigger: 'always',
        },
      },
      // Link Ribbon
      {
        id: 'el_6',
        name: 'Hyperlink Action',
        type: 'link',
        content: '⚡ PROTOCOL OVERRIDE // VISIT ARCHIVE',
        linkUrl: 'https://example.com',
        colorMarker: '#6',
        useAttributeSelector: true,
        x: 180,
        y: 400,
        width: 360,
        height: 46,
        zIndex: 6,
        rotate: 0,
        opacity: 100,
        locked: false,
        hidden: false,
        color: '#fbbf24',
        backgroundColor: 'rgba(245, 158, 11, 0.15)',
        fontSize: 14,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fontFamily: 'inherit',
        borderWidth: 2,
        borderColor: '#f59e0b',
        borderStyle: 'solid',
        borderRadius: 4,
        boxShadow: '0 0 20px rgba(245, 158, 11, 0.4)',
        padding: 10,
        overflow: 'hidden',
        mask: {
          enabled: false,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 0,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: true,
          type: 'polygon',
          preset: 'badge',
          vertices: CLIP_PRESETS.badge.vertices,
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: true,
          preset: 'heartbeat',
          duration: 2,
          delay: 0,
          timing: 'ease-in-out',
          iteration: 'infinite',
          direction: 'normal',
          trigger: 'hover',
        },
      },
    ],
  },
  synthwave: {
    name: 'Synthwave 80s Sunset',
    description: 'Retro purple & sunset neon vibes with radial spotlight masks and floating badges.',
    settings: {
      width: 720,
      height: 580,
      backgroundColor: '#13091e',
      backgroundImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=70',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      gridSnap: true,
      gridSize: 10,
      showGrid: false,
      profileTitle: 'Synthwave Skyline Profile',
      forumTheme: 'synthwave',
    },
    elements: [
      {
        id: 'sw_1',
        name: 'Sun Avatar',
        type: 'image',
        content: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
        colorMarker: '#1',
        useAttributeSelector: true,
        x: 60,
        y: 50,
        width: 140,
        height: 140,
        zIndex: 5,
        rotate: 0,
        opacity: 100,
        locked: false,
        hidden: false,
        color: '#ec4899',
        backgroundColor: 'rgba(236, 72, 153, 0.2)',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecoration: 'none',
        textAlign: 'center',
        fontFamily: 'inherit',
        borderWidth: 3,
        borderColor: '#f43f5e',
        borderStyle: 'solid',
        borderRadius: 9999,
        boxShadow: '0 0 35px rgba(244, 63, 94, 0.6)',
        padding: 0,
        overflow: 'hidden',
        mask: {
          enabled: true,
          type: 'radial-gradient',
          preset: 'radial-spotlight',
          angle: 0,
          stops: [],
          feather: 30,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: false,
          type: 'polygon',
          preset: 'hexagon',
          vertices: [],
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: true,
          preset: 'float',
          duration: 3,
          delay: 0,
          timing: 'ease-in-out',
          iteration: 'infinite',
          direction: 'alternate',
          trigger: 'always',
        },
      },
      {
        id: 'sw_2',
        name: 'Retro Headline',
        type: 'text',
        content: '★ OUTRUN 1984 // PACIFIC COAST HIGHWAY ★',
        colorMarker: '#2',
        useAttributeSelector: true,
        x: 230,
        y: 50,
        width: 430,
        height: 52,
        zIndex: 6,
        rotate: 0,
        opacity: 100,
        locked: false,
        hidden: false,
        color: '#fb7185',
        backgroundColor: 'rgba(30, 10, 45, 0.85)',
        fontSize: 18,
        fontWeight: 'bold',
        fontStyle: 'italic',
        textDecoration: 'none',
        textAlign: 'center',
        fontFamily: 'Impact, sans-serif',
        borderWidth: 2,
        borderColor: '#f43f5e',
        borderStyle: 'solid',
        borderRadius: 8,
        boxShadow: '0 0 20px rgba(244, 63, 94, 0.4)',
        padding: 12,
        overflow: 'hidden',
        mask: {
          enabled: false,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 0,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: false,
          type: 'polygon',
          preset: 'hexagon',
          vertices: [],
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: true,
          preset: 'neonPulse',
          duration: 2,
          delay: 0,
          timing: 'ease-in-out',
          iteration: 'infinite',
          direction: 'alternate',
          trigger: 'always',
        },
      },
      {
        id: 'sw_3',
        name: 'Retro Quote',
        type: 'quote',
        content: '"Cruising towards the neon sunset with analog synthesizers humming in the tape deck."',
        colorMarker: '#3',
        useAttributeSelector: true,
        x: 230,
        y: 120,
        width: 430,
        height: 75,
        zIndex: 5,
        rotate: 0,
        opacity: 95,
        locked: false,
        hidden: false,
        color: '#e0e7ff',
        backgroundColor: 'rgba(20, 10, 35, 0.85)',
        fontSize: 15,
        fontWeight: 'normal',
        fontStyle: 'italic',
        textDecoration: 'none',
        textAlign: 'left',
        fontFamily: 'Trebuchet MS, sans-serif',
        borderWidth: 1,
        borderColor: '#a855f7',
        borderStyle: 'solid',
        borderRadius: 6,
        boxShadow: '0 8px 24px rgba(168, 85, 247, 0.3)',
        padding: 14,
        overflow: 'hidden',
        mask: {
          enabled: false,
          type: 'linear-gradient',
          preset: 'fade-bottom',
          angle: 180,
          stops: [],
          feather: 0,
          invert: false,
          shape: 'circle',
        },
        clip: {
          enabled: false,
          type: 'polygon',
          preset: 'hexagon',
          vertices: [],
          circleRadius: 50,
          circleCenterX: 50,
          circleCenterY: 50,
          insetRadius: 0,
        },
        animation: {
          enabled: false,
          preset: 'float',
          duration: 3,
          delay: 0,
          timing: 'ease',
          iteration: 'infinite',
          direction: 'normal',
          trigger: 'always',
        },
      },
    ],
  },
};
